package com.letsride.lets_ride_backend.entity; // Add the underscore

import jakarta.persistence.*;
import lombok.Getter; // Optional Lombok annotations
import lombok.Setter; // Optional Lombok annotations
import lombok.NoArgsConstructor; // Optional Lombok annotations
import lombok.AllArgsConstructor; // Optional Lombok annotations

@Entity // Marks this class as a JPA entity (mapped to a table named "user")
@Table(name = "app_user") // Explicitly names the table "app_user" (User is often a reserved word)
@Getter // Lombok: Creates getter methods for all fields
@Setter // Lombok: Creates setter methods for all fields
@NoArgsConstructor // Lombok: Creates a no-argument constructor
@AllArgsConstructor // Lombok: Creates a constructor with all arguments
public class User {

    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-generates the ID value
    private Long id;

    @Column(nullable = false, unique = true) // Database column constraints
    private String email;

    @Column(nullable = false)
    private String password; // Store hashed password, not plain text!

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private String role; // e.g., "RIDER", "DRIVER", "ADMIN" (Consider using an Enum later)

    // We will add relationships (e.g., to ScheduledTrips, Bookings) later
    // We will add fields like rate_per_mile for drivers later (Phase 2 or if needed for pricing)

    // Constructors, Getters, Setters are generated by Lombok if used.
    // If not using Lombok, you need to write them manually.
}